version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_erudio2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - erudio2_data:/var/lib/mysql

volumes:
  erudio2_data:
