server:
  error:
    include-stacktrace: on_param
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  flyway:
    locations: src/main/resources/db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    ring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        flywaydb: DEBUG
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
