server:
  error:
    include-stacktrace: on_param
file:
  upload-dir: /home/felix/uploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_erudio?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    ring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart":
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        flywaydb: DEBUG
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
