name: Continuous Integration with Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2.3.0
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application JAR
      working-directory: ./
      run: mvn clean package -DskipTests -Dmaven.test.skip=true
      

    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:latest rodrigofelixf/rest_with_spring_boot_erudio:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest_with_spring_boot_erudio:latest
